---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-storage
  namespace: gb-devops-conteiner-hw05
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-ssd-gz1"